Dockerfile, package-lock.json, package.json, tsconfig.json
Added unsafe prem flag to allow patching a dependency.
=> fix: add unsafe prem to allow patching

package-lock.json, package.json, src/common/translations/record-3d-fields.translation.ts
3D model updated
| New feature     | ✔/✖                                                                        |
=> fix: update 3d model

src/common/ingestion-manager/ingestion-manager-3d.ts, src/common/ui-aspects/record-3d-fields.ui-aspects.ts
=> feat: integration with 3D

config/default.json, package-lock.json, package.json, src/AUTOGENERATED/GraphQLClass.ts, src/common/ingestion-manager/ingestion-manager-3d.ts, src/common/ui-aspects/record-3d-fields.ui-aspects.ts
=> feat: bump version

config/default.json, src/csw/csw.ts, src/csw/cswClientWrapper.ts, src/graphql/inputTypes.ts, src/graphql/resolvers/csw.resolver.ts
=> feat: get records by id

src/csw/cswClientWrapper.ts
Resolve/parse discretes value (array)
| Bug fix         | ✔/✖                                                                        |
=> fix: prepare discretes actual value

config/custom-environment-variables.json, config/default.json, src/csw/csw.ts
Ability to work against configured entity types
| New feature     | ✔/✖                                                                        |
=> feat: served entity types

src/common/ui-aspects/record-3d-fields.ui-aspects.ts, src/common/ui-aspects/record-best-fields.ui-aspects.ts, src/common/ui-aspects/record-raster-fields.ui-aspects.ts
=> fix: for validations

src/graphql/entityDescriptor.ts
=> fix: value type enum name

config/custom-environment-variables.json
=> fix: dem csw from config

src/common/catalog-manager/catalog-manager-dem.ts, src/common/ingestion-manager/ingestion-manager-dem.ts, src/common/ui-aspects/record-dem-fields.ui-aspects.ts
=> fix: dem view mode

src/graphql/job.ts
=> fix: jobs product type

src/graphql/inputTypes.ts, src/graphql/job.ts, src/graphql/resolvers/job.resolver.ts, src/graphql/resolvers/task.resolver.ts
Fix tasks fetching API endpoint
=> fix: task fetching and linting

package-lock.json, package.json, src/common/ui-aspects/record-3d-fields.ui-aspects.ts
=> fix: tooltips

src/common/ui-aspects/record-dem-fields.ui-aspects.ts
=> fix: missing is copyable

src/graphql/resolvers/job.resolver.ts
=> feat: added job retry service

.licrc, package-lock.json, package.json
=> chore: upgrade mc models version

config/default.json
DEM default vars
| Bug fix         | ✔/✖                                                                        |
=> fix: dem defaults

src/common/catalog-manager/catalog-manager-3d.ts, src/common/catalog-manager/catalog-manager-raster.ts, src/common/ingestion-manager/ingestion-manager-3d.ts, src/common/ingestion-manager/ingestion-manager-raster.ts, src/graphql/resolvers/csw.resolver.ts, src/graphql/resolvers/job.resolver.ts
=> chore: remove unused lint ignore remarks

src/graphql/resolvers/job.resolver.ts
=> fix: jobs without tasks api call

src/common/ingestion-manager/ingestion-manager-raster.ts, src/utils.ts
| Bug fix         | ✔                                                                       |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖ …
=> fix: raster ingestion - expected relative dir path

config/custom-environment-variables.json
=> fix: token var name

config/default.json, src/graphql/MOCKS/service-discovery/depAndServicesMock.ts, src/graphql/external-services.ts, src/graphql/resolvers.ts, src/graphql/resolvers/external-services.resolver.ts, src/graphql/resolvers/service-discovery.resolver.ts, src/graphql/service-discovery.ts
added config, resolver and types for external services
=> feat: external services config  implementation

src/common/capabilities-manager/capabilities-manager-dem.ts, src/common/capabilities-manager/capabilities-manager-raster.ts, src/common/capabilities-manager/capabilities-manager.interface.ts, src/common/capabilities-manager/capabilities-manager.ts, src/graphql/inputTypes.ts, src/graphql/resolvers/capabilities.resolver.ts
=> fix: capabilities

src/common/capabilities-manager/capabilities-manager-dem.ts, src/common/capabilities-manager/capabilities-manager-raster.ts
fix DEM  getCapabilities url(added hardcoded value for geoserver wmts capabilities)
=> fix: get dem get capabilities url

package.json
=> chore: bump v1.10.4

src/csw/cswClientWrapper.ts
=> fix: sync footprint

package-lock.json, package.json, src/AUTOGENERATED/GraphQLClass.ts
=> mc models id changes

src/graphql/job.ts, src/graphql/resolvers/job.resolver.ts
=> fix: abort job status support + disable job actions

src/AUTOGENERATED/GraphQLClass.ts
=> Enum presentor 

src/common/ui-aspects/record-raster-fields.ui-aspects.ts
fix raster insertdate granularity
=> fix: raster insertdate granularity

config/default.json, package-lock.json, package.json, src/graphql/entityDescriptor.ts, src/graphql/lookupTablesData.ts, src/graphql/resolvers.ts, src/graphql/resolvers/lookup-table.resolver.ts
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore …
=> feat: Lookup tables integration

package-lock.json, package.json, src/common/ui-aspects/record-best-fields.ui-aspects.ts, src/common/ui-aspects/record-raster-fields.ui-aspects.ts
raster productType should be frozen on updated
=> fix: ptoduct type freeze on update

src/common/ui-aspects/record-3d-fields.ui-aspects.ts, src/common/ui-aspects/record-best-fields.ui-aspects.ts, src/common/ui-aspects/record-dem-fields.ui-aspects.ts, src/common/ui-aspects/record-quantized-mesh-best-fields.ui-aspects.ts, src/common/ui-aspects/record-raster-fields.ui-aspects.ts, src/common/ui-aspects/record-vector-best-fields.ui-aspects.ts, src/graphql/entityDescriptor.ts, src/helpers/entityDescriptor.helpers.ts
| Bug fix         | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   |✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            |✖ …
=> Catalog filters

src/common/ui-aspects/record-3d-fields.ui-aspects.ts, src/common/ui-aspects/record-best-fields.ui-aspects.ts, src/common/ui-aspects/record-dem-fields.ui-aspects.ts, src/common/ui-aspects/record-quantized-mesh-best-fields.ui-aspects.ts, src/common/ui-aspects/record-raster-fields.ui-aspects.ts, src/helpers/entityDescriptor.helpers.ts, src/serverBuilder.ts
- Support the fix for export layer error presenting, Combined "Status Text" With error messages.
- Catalog filters text fields should support also [' " ,] (UI ASPECTS)
Related issues: 
MAPCO-3251
=> fix:  v2.1.1 bugs and improvements

src/common/ui-aspects/record-raster-fields.ui-aspects.ts, src/graphql/entityDescriptor.ts, src/graphql/resolvers/lookup-table.resolver.ts
Ability to add custom lookup-tables for client as well new decorators for dependent fields
=> feat: resolution as custom lookup-table (zoomlevelresolutions) ( MAPCO-3631 )

package-lock.json, package.json
3d profile update (3 fields startDate, endDate and footprint now opened for EDITING)
=> chore: bump mc-models 15-1-1

src/utils.ts
| Bug fix         | ✔/✖                                                                        |
=> fix: axios default retry mechanism ( MAPCO-4413 )

src/graphql/inputTypes.ts, src/wfs/wfs-client/constants.ts, src/wfs/wfs-client/interfaces.ts, src/wfs/wfs-client/wfs-client.ts
=> feat: support wfs pagination
